enable-module-update = true # set this to false if you do not want to receive updates for the module
parallel-jobs = 1

# add 'enabled = false' for not patching a specific app or remove it from the config
# see https://github.com/j-hc/revanced-magisk-module/blob/main/CONFIG.md for more detailed explanations

# you can use rvmm-config-gen to generate a config


[YouTube-Morphe]
app-name = "YouTube"
patches-source = "MorpheApp/morphe-patches"
cli-source = "MorpheApp/morphe-cli"
rv-brand = "Morphe"
build-mode = "both"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube"
uptodown-dlurl = "https://youtube.en.uptodown.com/android"
archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.google.android.youtube"

[Music-Morphe]
app-name = "Music"
patches-source = "MorpheApp/morphe-patches"
cli-source = "MorpheApp/morphe-cli"
rv-brand = "Morphe"
build-mode = "both"
arch = "both"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube-music"
uptodown-dlurl = "https://youtube-music.en.uptodown.com/android"
archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.google.android.apps.youtube.music"

[CaitlinGram]
apkmirror-dlurl = "https://apkmirror.com/apk/instagram/instagram-instagram/"
version = "beta"
included-patches = "'Hide ads' 'Enable developer menu' 'Disable analytics' 'Remove build expired popup' 'Sanitize sharing links'"
exclusive-patches = true

[CaitlinMusic]
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube-music/"
excluded-patches = "'Permanent repeat' 'Custom branding' 'Hide buttons' 'Hide category bar' 'Hide layout components' 'Change miniplayer color'"

[CaitlinTube]
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube/"
excluded-patches = "'Custom branding' 'Change header' 'Hide video action buttons' 'Navigation buttons' 'Hide player overlay buttons' 'Hide end screen cards' 'Hide end screen suggested video' 'Disable fullscreen ambient mode' 'Hide layout components' 'Hide info cards' 'Hide related video overlay' 'Disable rolling number animations' 'Hide Shorts components' 'Disable sign in to TV popup' 'Hide timestamp' 'Wide search bar' 'Open Shorts in regular player' 'Change start page' 'Disable resuming Shorts on startup' 'Alternative thumbnails' 'Announcements'"

[CaitlinPhotos]
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/photos/"

[CaitlinLightroom]
apkmirror-dlurl = "https://www.apkmirror.com/apk/adobe/lightroom/"

[Spotify]
apkmirror-dlurl = "https://www.apkmirror.com/apk/spotify-ab/spotify-music-podcasts/y.yCYTaVJFMfIUVXcGAx2BYk8XjWo"
